In [6]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)
data = np.genfromtxt("classification.txt", delimiter=",")
learningRate = 0.01
data = np.delete(data, [3], axis=1)  # deletinig the 4th column
Y = data[:, -1]
X_train = np.delete(data, [3], axis=1)
oneVector = np.ones((X_train.shape[0], 1))
X_train = np.concatenate((oneVector, X_train), axis=1)
# xa = X_train[0].reshape(-1,X_train.shape[1])
print (X_train)
print(Y)
plotData = []
weights = np.random.rand(4, 1)
misClassifications = 1
minMisclassifications = 10000
iteration = 0
while (misClassifications != 0 and (iteration<10)):
    iteration += 1
    misClassifications = 0
    for i in range(0, len(X_train)):
        currentX = X_train[i].reshape(-1, X_train.shape[1])
        currentY = Y[i]
        wTx = np.dot(currentX, weights)[0][0]
        if currentY == 1 and wTx < 0:
            misClassifications += 1
            weights = weights + learningRate * np.transpose(currentX)
        elif currentY == -1 and wTx > 0:
            misClassifications += 1
            weights = weights - learningRate * np.transpose(currentX)
    plotData.append(misClassifications)
    if misClassifications<minMisclassifications:
        minMisclassifications = misClassifications
    # if iteration%1==0:
        print("Iteration {}, Misclassifications {}".format(iteration, misClassifications))
print ("Minimum Misclassifications : ",minMisclassifications)
print ("Best Case Accuracy of Pocket Learning Algorithm is: ",(((X_train.shape[0]-minMisclassifications)/X_train.shape[0])*100),"%")
# print("Number of misclassifications: ", misClassifications)


[[1.         0.750072   0.97740794 0.88565752]
 [1.         0.87791369 0.01925101 0.50671112]
 [1.         0.7773246  0.99406596 0.82224385]
 ...
 [1.         0.5155064  0.15354364 0.01275495]
 [1.         0.2282263  0.97155357 0.18305906]
 [1.         0.36391513 0.49207061 0.71952659]]
[ 1. -1.  1. ...  1.  1.  1.]
Iteration 1, Misclassifications 995
Iteration 2, Misclassifications 986
Iteration 6, Misclassifications 981
Iteration 9, Misclassifications 976
Iteration 10, Misclassifications 975
Minimum Misclassifications :  975
Best Case Accuracy of Pocket Learning Algorithm is:  51.24999999999999 %
